### ISSUE TITLE
How to generate from a string?

### ISSUE THREAD

**Issue by matheus-moreira** [shootingfly/water#2]
Supposing that i have a string that will be read from a file, ex.:

```
head {
  meta %|name="viewport" content="width=device-width,initial-scale=1.0"|
  title "This is a tile"
}
```

I wanna do:

```
html_head = Water.new do
   "#{head}"
end
```

or something like that...

Which would be basically the include function that exists in other libraries... but it doesnt work. Is there a way to do this?

Thank you for time and patience.

**Comment by matheus-moreira** [comment]
Just realized that this is possible using kilt

**Comment by shootingfly** [comment]
@matheus-moreira I will regard it as partial view and use `read_file` macro. You can see an example of runcobo, a general framework made by me. https://runcobo.github.io/docs/html/

Also you can define another macro about read_file.
```crystal
{{ read_file("src/views/books/table.water").id }}
```

**Comment by matheus-moreira** [comment]
Thank you :)
